version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: tayyab/nestapp:1.0.0
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_TYPE: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: newpassword
      DATABASE_NAME: crudapi-with-docker
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=newpassword
      - POSTGRES_DB=crudapi-with-docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
